// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8LBGuYiUHUS2hrVgnKVmaCMetNrvhhsg',
    appId: '1:43076874233:android:fe72df0538a0c0cbe01728',
    messagingSenderId: '43076874233',
    projectId: 'shelf-credes',
    storageBucket: 'shelf-credes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw592bqOrmqwY5O2Ut-jpw9clZIUOuAY4',
    appId: '1:43076874233:ios:18809ef3eb4cb9bfe01728',
    messagingSenderId: '43076874233',
    projectId: 'shelf-credes',
    storageBucket: 'shelf-credes.firebasestorage.app',
    androidClientId: '43076874233-gdj82bu2dp1d2c6o6btr9q32q14b9844.apps.googleusercontent.com',
    iosClientId: '43076874233-89pc398ggv5bi2gr96440j7153lhhjmu.apps.googleusercontent.com',
    iosBundleId: 'org.shelf.shelf',
  );

}